#!/usr/bin/env ruby
# Encoding: utf-8
##
# Copyright IBM Corporation 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

require 'fileutils'

# directories
INSTALL_DIR = File.expand_path('../../..', File.dirname(__FILE__)).freeze
APP_MGMT_DIR = File.join(INSTALL_DIR, '.app-management').freeze

$LOAD_PATH.unshift File.expand_path(APP_MGMT_DIR, __FILE__)

# These require stamements must be executed after the LOAD_PATH array is updated.
require 'utils/droplet_utils.rb'
require 'utils/handler_utils.rb'
require 'utils/simple_logger.rb'

config = Utils::HandlerUtils.get_configuration('debug')
port = config['port'] || DropletUtils.find_port(7777, 8777)

#pid = spawn("lldb-server platform --listen *:#{port}", :out => "#{APP_MGMT_DIR}/lldb-server.out", :err => "#{APP_MGMT_DIR}/lldb-server.err")
pid = spawn("swift", :out => "#{APP_MGMT_DIR}/lldb-server.out", :err => "#{APP_MGMT_DIR}/lldb-server.err")
Process.detach(pid)
pgid = Process.getpgid(pid)

Utils::SimpleLogger.info("lldb-server (pid: #{pid}, pgid: #{pgid}) is listening on port #{port}.")

system("ps", "-ef", out: $stdout, err: :out)
system("cat", "#{APP_MGMT_DIR}/lldb-server.out", out: $stdout, err: :out)
system("cat", "#{APP_MGMT_DIR}/lldb-server.err", out: $stdout, err: :out)


#{}`ps -ef | grep #{pid}`
#{}`cat #{APP_MGMT_DIR}/lldb-server.out`
#{}`cat #{APP_MGMT_DIR}/lldb-server.err`
