#!/usr/bin/env bash
##
# Copyright IBM Corporation 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

if [ -z "$1" ]; then
  echo "A port parameter is required!"
  exit 1
fi

export PORT="$1"
if [ -n "$VCAP_APP_PORT" ]; then
  export VCAP_APP_PORT=$1
fi

BREAK="${2:-no-break}" # This form sets BREAK to "no-break" if $2 is empty

app_dir=$(cd `dirname $0`/../.. && pwd)
cd $app_dir
app_management_dir=$(cd .app-management && pwd)

echo "Starting app with '${NODE_EXECUTABLE} ${NODE_OPTS} ${BOOT_SCRIPT} ${NODE_ARGS}'"
${NODE_EXECUTABLE} ${NODE_OPTS} ${BOOT_SCRIPT} ${NODE_ARGS} &

# The percent-delimited COMMAND is a template variable that will get updated with the proper values during staging.
%COMMAND%

pid=$!
# Write the PID to a file
echo "${pid}" > $HOME/runtime.pid
wait $pid
